### ISSUE TITLE
煦涵说CSS（七）：scroll-behavior实现页面平滑滚动

### ISSUE THREAD

**Issue by zuojj** [zuojj/fedlab#17]
号外！！！Chrome 61 已经支持[scroll-behavior](https://drafts.csswg.org/cssom-view/#smooth-scrolling)属性，该属性指定滚动框(scrolling box)的滚动行为，当滚动行为由浏览器或者是CSSOM API发出时（例如点击锚点之后进行跳转）就会触发这个属性，但如果是用户滚动滚动条等操作时并不会触发这个属性。 当我们在根元素上使用该属性时，该属性会作用于 viewport 上。[Demo直达](https://github.com/zuojj/fedlab/blob/master/demos/scroll-behavior/scroll-behavior.html)

> `body` 元素上使用 `scroll-behavior` 不会冒泡到 viewport 上。

## scroll-behavior可取值

```css
div {
    scroll-behavior: [auto | smooth];
}

```

### auto
默认值，滚动框以即时方式滚动

### smooth
滚动框以平滑的方式滚动，使用 `user-agent-defined` 的定时函数在 `user-agent-defined` 定义的时间内滚动，如果有 user-agent 应该遵循平台约定。

## 浏览器兼容性
* Chrome 61+
* Friefox 36+

### auto
```js
window.scrollTo(x, y);
```

### smooth
使用 `window.setTimeout()`、`window.setInterval()` 或者 `window.requestAnimationFrame()` 分片滚动，以实现平滑效果。
```js
let scrollTo = function (position, timeout) {
    var scrollTop = document.documentElement.scrollTop || document.body.scrollTop,
        direction = position - scrollTop > 0 ? 1 : -1,
        distance = Math.abs(position - scrollTop),
        split = distance / 50,
        _timeout;

    if (position !== scrollTop) {
        timeout = timeout || 1000;
        split *= direction;

        _timeout = setInterval(function () {
            scrollTop += split;
            distance -= Math.abs(split);
            if (0 >= distance) {
                window.scrollTo(0, position);
                clearInterval(_timeout);
                _timeout = null;
            } else {
                window.scrollTo(0, scrollTop);
            }
        }, timeout / 100);
    }
};

```

感谢您的阅读

<div style="margin:5px auto;padding-top:1.2em;padding-bottom:0.6em;">
    <div style="font-size:1em; border-style: solid none none; border-top-width: 1px; border-color: rgb(17, 17, 17); color: rgb(204, 204, 204);"></div>
    <div style="margin-top: -0.7em;text-align:center;line-height:1.4;">
    <span style="padding:8px 23px;background-color:#fff;color:#000;margin-top:-1em;">EOF</span>
    </div>
</div>

<p style="font-size: 12px; color: #8e8e8e">作者[煦涵]</p>
<p style="font-size: 12px; color: #8e8e8e">2017年09月26日</p>

<div style="text-align: center; font-size: 12px; color: #8e8e8e;">
    <div>下面是「FED实验室」的微信公众号二维码，欢迎扫描关注：</div>
    <img src="https://cloud.githubusercontent.com/assets/5378965/26525703/ba3707ac-4392-11e7-8a99-db27837f9c3c.jpg" alt="关注FED实验室" title="关注FED实验室">
</div>

**Comment by william807803** [comment]
很有用，解决了我的问题，thank u !

**Comment by zuojj** [comment]
> 很有用，解决了我的问题，thank u !

**Comment by mdxayw** [comment]
very very good!!!点赞

**Comment by 13836005450** [comment]
很有用，也解决了我的问题，平滑滚动必备代码！scroll-behavior: smooth;这个属性兼容性太差了，已经换用博主的方法了，感谢
